main: com.gmail.qwerty12944qwerty.pgjigsaw.main.Main
name: PG-Jigsaw
version: 1.4.0
api-version: 1.13
author: 12944qwerty
description: Party Game Jigsaw rush practice
commands:
  afk:
    description: Toggles your afk status
    usage: /afk
  start:
    description: Start the game
    usage: /start
  end:
    description: End the game
    usage: /end